package view;

import controller.MainController;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author r4wd3r
 */
public class AddVehiclePanel extends javax.swing.JPanel {

    /** Creates new form AddVehiclePanel */
    public AddVehiclePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddVehicleButton = new javax.swing.JButton();
        VehicleTypeCombobox = new javax.swing.JComboBox();
        VehicleTypeLabel = new javax.swing.JLabel();
        ComentaryLabel = new javax.swing.JLabel();
        ComentaryScroll = new javax.swing.JScrollPane();
        ComentaryArea = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddVehicleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add.png"))); // NOI18N
        AddVehicleButton.setText("Ingresar");
        AddVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVehicleButtonActionPerformed(evt);
            }
        });
        add(AddVehicleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        VehicleTypeCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(VehicleTypeCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 0, -1, -1));

        VehicleTypeLabel.setText("Tipo de Vehículo:");
        add(VehicleTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, -1, -1));

        ComentaryLabel.setText("Comentarios:");
        add(ComentaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, -1, -1));

        ComentaryArea.setColumns(20);
        ComentaryArea.setRows(5);
        ComentaryScroll.setViewportView(ComentaryArea);

        add(ComentaryScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, 410, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {                                    
    DefaultComboBoxModel model = MainController.addVehicleController.getModelComboBox(
            MainController.mainView.getPlate());
    if (model.getSize() == 0) {
       JOptionPane.showMessageDialog(null, "Tipo de placa no existente, "
               + "por favor, inserte un tipo de placa valido", "error", WIDTH);
    } else {
        VehicleTypeCombobox.setModel(model);
        VehicleTypeCombobox.updateUI();
    }

    }
    
    public void setVehicleTypeCombobox(DefaultComboBoxModel model){
        this.VehicleTypeCombobox.setModel(model);
    }

    public void setComentaryArea(String text) {
        this.ComentaryArea.setText(text);
    }
    
    private void AddVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVehicleButtonActionPerformed
        String id = (String) VehicleTypeCombobox.getSelectedItem();
        MainController.addVehicleController.CreateVehicle(id, ComentaryArea.getText());
        MainController.mainView.setPlateTextField("");  
    }//GEN-LAST:event_AddVehicleButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddVehicleButton;
    private javax.swing.JTextArea ComentaryArea;
    private javax.swing.JLabel ComentaryLabel;
    private javax.swing.JScrollPane ComentaryScroll;
    private javax.swing.JComboBox VehicleTypeCombobox;
    private javax.swing.JLabel VehicleTypeLabel;
    // End of variables declaration//GEN-END:variables
}
