/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdministrationView.java
 *
 * Created on 06-oct-2011, 13:08:24
 */
package view;

import DAO.exceptions.PreexistingEntityException;
import Entity.Employee;
import Entity.VehicleType;
import controller.Administration.AdministrateEmployeeController;
import controller.Administration.AdministrateBandRates;
import controller.Administration.AdministrateVehicleTypeController;
import controller.Administration.AdministrationController;
import controller.MainController;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author r4wd3r
 */
public class AdministrationView extends javax.swing.JFrame {

    /** Creates new form AdministrationView */
    public AdministrationView() {
        initComponents();


    }

    public JList getEmployeeList() {
        return EmployeeList;
    }

    public void setEmployeeList(JList EmployeeList) {
        this.EmployeeList = EmployeeList;
    }

    public JTable getPlatesTable() {
        return PlatesTable;
    }

    public void setPlatesTable(JTable PlatesTable) {
        this.PlatesTable = PlatesTable;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        AdminTabbedPanel = new javax.swing.JTabbedPane();
        ParkwayAdminPanel = new javax.swing.JPanel();
        NameParkwayTextField = new javax.swing.JTextField();
        NameParkwayLabel = new javax.swing.JLabel();
        AddressTextField = new javax.swing.JTextField();
        TelephoneTextField = new javax.swing.JTextField();
        NITParkwayTextField = new javax.swing.JTextField();
        MaxCapacityTextField = new javax.swing.JTextField();
        AddressParkwayLabel = new javax.swing.JLabel();
        NITParkwayLabel = new javax.swing.JLabel();
        TelephoneParkwayLabel = new javax.swing.JLabel();
        MaxCapacityLabel = new javax.swing.JLabel();
        SaveParkwayChangesButton = new javax.swing.JButton();
        EmployeeAdminPanel = new javax.swing.JPanel();
        EmployeeListScroll = new javax.swing.JScrollPane();
        EmployeeList = new javax.swing.JList();
        EmployeeListLabel = new javax.swing.JLabel();
        IdEmployeeTextField = new javax.swing.JTextField();
        IdEmployeeLabel = new javax.swing.JLabel();
        NameEmployeeTextField = new javax.swing.JTextField();
        LastNameEmployeeTextField = new javax.swing.JTextField();
        DocumentEmployeeTextField = new javax.swing.JTextField();
        NameEmployeeLabel = new javax.swing.JLabel();
        LastNameEmployeeLabel = new javax.swing.JLabel();
        DocumentEmployeeLabel = new javax.swing.JLabel();
        isAdminEmployeeCheckBox = new javax.swing.JCheckBox();
        CreateEmployeeButton = new javax.swing.JButton();
        UpdateEmployeeButton = new javax.swing.JButton();
        ConsultEmployeeTextField = new javax.swing.JTextField();
        SearchEmployeeLabel = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        UserLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UserTextField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        isActiveEmployeeCheckBox = new javax.swing.JCheckBox();
        RateAdminPanel = new javax.swing.JPanel();
        RatesScroll = new javax.swing.JScrollPane();
        RatesTable = new javax.swing.JTable();
        VehicleTypeLabel = new javax.swing.JLabel();
        VehicleTypeComboBox = new javax.swing.JComboBox();
        SaveRateChangesButton = new javax.swing.JButton();
        PlateAdmin = new javax.swing.JPanel();
        PlateSampleLabel = new javax.swing.JLabel();
        PlateExampleTextField = new javax.swing.JTextField();
        VehicleTypeNameLabel = new javax.swing.JLabel();
        SavePlateButton = new javax.swing.JButton();
        IdentifierPlateTextField = new javax.swing.JTextField();
        VehicleTypeScroll = new javax.swing.JScrollPane();
        PlatesTable = new javax.swing.JTable();
        ReportAdminPanel = new javax.swing.JPanel();
        ReportTypeCombo = new javax.swing.JComboBox();
        ReportTypeLabel = new javax.swing.JLabel();
        StartDateReportLabel = new javax.swing.JLabel();
        LastDateReportLabel = new javax.swing.JLabel();
        StartDateReportSpinner = new javax.swing.JSpinner();
        LastDateReportSpinner = new javax.swing.JSpinner();
        ReportScroll = new javax.swing.JScrollPane();
        ReportTable = new javax.swing.JTable();
        GenerateReportButton = new javax.swing.JButton();

        jLabel12.setText("jLabel12");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ExitButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        ExitButton.setText("Cerrar");
        ExitButton.setToolTipText("Terminar la configuración.");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        AdminTabbedPanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AdminTabbedPanelFocusGained(evt);
            }
        });

        ParkwayAdminPanel.setBackground(new java.awt.Color(254, 254, 254));

        NameParkwayTextField.setToolTipText("Ingrese el nombre de su negocio.");

        NameParkwayLabel.setText("Nombre:");

        AddressTextField.setToolTipText("Ingrese la dirección de su negocio.");

        TelephoneTextField.setToolTipText("Ingrese el teléfono de su negocio.");

        NITParkwayTextField.setToolTipText("Ingrese el número del NIT de su negocio.");

        MaxCapacityTextField.setToolTipText("Ingrese la capacidad máxima de su negocio.");

        AddressParkwayLabel.setText("Dirección:");

        NITParkwayLabel.setText("NIT:");

        TelephoneParkwayLabel.setText("Teléfono:");

        MaxCapacityLabel.setText("Capacidad Máxima:");

        SaveParkwayChangesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Database.png"))); // NOI18N
        SaveParkwayChangesButton.setText("Guardar Cambios");
        SaveParkwayChangesButton.setToolTipText("Cambia los datos de la base de datos según los cambios.");
        SaveParkwayChangesButton.setEnabled(false);

        javax.swing.GroupLayout ParkwayAdminPanelLayout = new javax.swing.GroupLayout(ParkwayAdminPanel);
        ParkwayAdminPanel.setLayout(ParkwayAdminPanelLayout);
        ParkwayAdminPanelLayout.setHorizontalGroup(
            ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParkwayAdminPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameParkwayLabel)
                    .addComponent(NITParkwayLabel)
                    .addComponent(MaxCapacityLabel)
                    .addComponent(AddressParkwayLabel)
                    .addComponent(TelephoneParkwayLabel))
                .addGap(35, 35, 35)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TelephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ParkwayAdminPanelLayout.createSequentialGroup()
                        .addComponent(NITParkwayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(SaveParkwayChangesButton))
                    .addComponent(NameParkwayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaxCapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        ParkwayAdminPanelLayout.setVerticalGroup(
            ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParkwayAdminPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameParkwayLabel)
                    .addComponent(NameParkwayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddressParkwayLabel)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NITParkwayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NITParkwayLabel)
                    .addComponent(SaveParkwayChangesButton))
                .addGap(12, 12, 12)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelephoneParkwayLabel)
                    .addComponent(TelephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaxCapacityLabel)
                    .addComponent(MaxCapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        AdminTabbedPanel.addTab("Administrar Parqueadero", ParkwayAdminPanel);

        EmployeeAdminPanel.setBackground(new java.awt.Color(254, 254, 254));

        EmployeeListScroll.setToolTipText("Empleados registrados en el sistema.");

        EmployeeList.setToolTipText("Empleados registrados en el sistema.");
        EmployeeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                EmployeeListValueChanged(evt);
            }
        });
        EmployeeListScroll.setViewportView(EmployeeList);

        EmployeeListLabel.setText("Lista de Empleados:");

        IdEmployeeTextField.setEditable(false);
        IdEmployeeTextField.setToolTipText("Identificador de empleado (No editable)");

        IdEmployeeLabel.setText("ID:");

        NameEmployeeTextField.setToolTipText("Nombre empleado.");
        NameEmployeeTextField.setEnabled(false);

        LastNameEmployeeTextField.setToolTipText("Apellido empleado.");
        LastNameEmployeeTextField.setEnabled(false);

        DocumentEmployeeTextField.setToolTipText("Documento empleado.");
        DocumentEmployeeTextField.setEnabled(false);

        NameEmployeeLabel.setText("Nombre:");

        LastNameEmployeeLabel.setText("Apellidos:");

        DocumentEmployeeLabel.setText("Documento:");

        isAdminEmployeeCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        isAdminEmployeeCheckBox.setText("Administrador");
        isAdminEmployeeCheckBox.setToolTipText("Seleccione aquí para dar permisos de Administador al empleado cuya información aparece arriba.");
        isAdminEmployeeCheckBox.setEnabled(false);

        CreateEmployeeButton.setText("Crear Empleado");
        CreateEmployeeButton.setToolTipText("Crear un nuevo empleado de acuerdo a lo ingresado.");
        CreateEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateEmployeeButtonActionPerformed(evt);
            }
        });

        UpdateEmployeeButton.setText("Actualizar Empleado");
        UpdateEmployeeButton.setToolTipText("Actualizar un empleado existente con la información ingresada.");

        ConsultEmployeeTextField.setToolTipText("Ingrese el código del empleado que desee buscar.");

        SearchEmployeeLabel.setText("Buscar:");

        SearchButton.setText("Buscar");
        SearchButton.setToolTipText("Buscar empleado en el sistema, si deja vacío el espacio a su izquierda buscará todos los empleados.");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        UserLabel.setText("Usuario:");

        PasswordLabel.setText("Contraseña:");

        UserTextField.setToolTipText("Nombre con que el empleado accederá al sistema.");
        UserTextField.setEnabled(false);

        PasswordField.setToolTipText("Contraseña con al que el empleado accederá al sistema.");
        PasswordField.setEnabled(false);

        isActiveEmployeeCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        isActiveEmployeeCheckBox.setText("Activo");
        isActiveEmployeeCheckBox.setToolTipText("Seleccione aquí para permitir al empleado acceso al sistema.");
        isActiveEmployeeCheckBox.setEnabled(false);

        javax.swing.GroupLayout EmployeeAdminPanelLayout = new javax.swing.GroupLayout(EmployeeAdminPanel);
        EmployeeAdminPanel.setLayout(EmployeeAdminPanelLayout);
        EmployeeAdminPanelLayout.setHorizontalGroup(
            EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                        .addComponent(EmployeeListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                                .addComponent(isAdminEmployeeCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(isActiveEmployeeCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IdEmployeeLabel)
                                    .addComponent(NameEmployeeLabel)
                                    .addComponent(LastNameEmployeeLabel)
                                    .addComponent(DocumentEmployeeLabel)
                                    .addComponent(UserLabel)
                                    .addComponent(PasswordLabel))
                                .addGap(49, 49, 49)
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PasswordField)
                                    .addComponent(UserTextField)
                                    .addComponent(DocumentEmployeeTextField)
                                    .addComponent(IdEmployeeTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NameEmployeeTextField)
                                    .addComponent(LastNameEmployeeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))))
                        .addGap(75, 75, 75)
                        .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CreateEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UpdateEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(EmployeeListLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeAdminPanelLayout.createSequentialGroup()
                        .addComponent(SearchEmployeeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsultEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchButton)
                        .addGap(248, 248, 248)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        EmployeeAdminPanelLayout.setVerticalGroup(
            EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchEmployeeLabel)
                    .addComponent(SearchButton))
                .addGap(28, 28, 28)
                .addComponent(EmployeeListLabel)
                .addGap(11, 11, 11)
                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IdEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdEmployeeLabel)
                            .addComponent(CreateEmployeeButton))
                        .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NameEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameEmployeeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LastNameEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LastNameEmployeeLabel)))
                            .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(UpdateEmployeeButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DocumentEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DocumentEmployeeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserLabel)
                            .addComponent(UserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PasswordLabel)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isAdminEmployeeCheckBox)
                            .addComponent(isActiveEmployeeCheckBox))))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        AdminTabbedPanel.addTab("Administrar Empleados", EmployeeAdminPanel);

        RateAdminPanel.setBackground(new java.awt.Color(254, 254, 254));

        RatesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Identificador", "Desde (Minuto)", "Hasta (Minuto)", "Fracción", "Valor Fracción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RatesScroll.setViewportView(RatesTable);

        VehicleTypeLabel.setText("Tipo de Vehículo:");

        new javax.swing.DefaultComboBoxModel(new String[] { "-" });
        VehicleTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                VehicleTypeComboBoxItemStateChanged(evt);
            }
        });

        SaveRateChangesButton.setText("Guardar cambios");
        SaveRateChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveRateChangesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RateAdminPanelLayout = new javax.swing.GroupLayout(RateAdminPanel);
        RateAdminPanel.setLayout(RateAdminPanelLayout);
        RateAdminPanelLayout.setHorizontalGroup(
            RateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RateAdminPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(VehicleTypeLabel)
                .addGap(52, 52, 52)
                .addComponent(VehicleTypeComboBox, 0, 226, Short.MAX_VALUE)
                .addGap(147, 147, 147)
                .addComponent(SaveRateChangesButton)
                .addGap(86, 86, 86))
            .addComponent(RatesScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );
        RateAdminPanelLayout.setVerticalGroup(
            RateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RateAdminPanelLayout.createSequentialGroup()
                .addGroup(RateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RateAdminPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(RateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VehicleTypeLabel)
                            .addComponent(VehicleTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RateAdminPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(SaveRateChangesButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(RatesScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        AdminTabbedPanel.addTab("Administrar Tarifas", RateAdminPanel);

        PlateAdmin.setBackground(new java.awt.Color(255, 255, 255));

        PlateSampleLabel.setText("Ejemplo de placa:");

        PlateExampleTextField.setFont(new java.awt.Font("Tahoma", 0, 24));
        PlateExampleTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PlateExampleTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PlateExampleTextFieldKeyReleased(evt);
            }
        });

        VehicleTypeNameLabel.setText("Nombre del tipo de vehiculo:");

        SavePlateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Database.png"))); // NOI18N
        SavePlateButton.setText("Guardar Placa");
        SavePlateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavePlateButtonActionPerformed(evt);
            }
        });
        SavePlateButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SavePlateButtonFocusGained(evt);
            }
        });

        PlatesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Identificador", "Tipo de Vehiculo", "Ejemplo de Placa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        VehicleTypeScroll.setViewportView(PlatesTable);
        PlatesTable.getColumnModel().getColumn(0).setMinWidth(20);
        PlatesTable.getColumnModel().getColumn(0).setPreferredWidth(80);
        PlatesTable.getColumnModel().getColumn(0).setMaxWidth(150);

        javax.swing.GroupLayout PlateAdminLayout = new javax.swing.GroupLayout(PlateAdmin);
        PlateAdmin.setLayout(PlateAdminLayout);
        PlateAdminLayout.setHorizontalGroup(
            PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlateAdminLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VehicleTypeNameLabel)
                    .addComponent(PlateSampleLabel))
                .addGap(18, 18, 18)
                .addGroup(PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlateExampleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(IdentifierPlateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addComponent(SavePlateButton)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlateAdminLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(VehicleTypeScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        PlateAdminLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {IdentifierPlateTextField, PlateExampleTextField});

        PlateAdminLayout.setVerticalGroup(
            PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlateAdminLayout.createSequentialGroup()
                .addGroup(PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlateAdminLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VehicleTypeNameLabel)
                            .addComponent(IdentifierPlateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PlateAdminLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(PlateSampleLabel)
                                .addGap(25, 25, 25))
                            .addGroup(PlateAdminLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(PlateExampleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44))
                    .addGroup(PlateAdminLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(SavePlateButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VehicleTypeScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        AdminTabbedPanel.addTab("Administrar Placas", PlateAdmin);

        ReportAdminPanel.setBackground(new java.awt.Color(254, 254, 254));

        ReportTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ReportTypeLabel.setText("Tipo de Reporte:");

        StartDateReportLabel.setText("Fecha de Inicio de reporte:");

        LastDateReportLabel.setText("Fecha de Terminacion de reporte:");

        StartDateReportSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));

        LastDateReportSpinner.setModel(new javax.swing.SpinnerDateModel());

        ReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ReportScroll.setViewportView(ReportTable);

        GenerateReportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Stationery.png"))); // NOI18N
        GenerateReportButton.setText("Generar");
        GenerateReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReportAdminPanelLayout = new javax.swing.GroupLayout(ReportAdminPanel);
        ReportAdminPanel.setLayout(ReportAdminPanelLayout);
        ReportAdminPanelLayout.setHorizontalGroup(
            ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportAdminPanelLayout.createSequentialGroup()
                .addGroup(ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReportAdminPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastDateReportLabel)
                            .addComponent(StartDateReportLabel)
                            .addComponent(ReportTypeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(StartDateReportSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ReportTypeCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 203, Short.MAX_VALUE))
                            .addComponent(LastDateReportSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(GenerateReportButton))
                    .addGroup(ReportAdminPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ReportScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ReportAdminPanelLayout.setVerticalGroup(
            ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportAdminPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ReportAdminPanelLayout.createSequentialGroup()
                        .addGroup(ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReportTypeLabel)
                            .addComponent(ReportTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StartDateReportSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StartDateReportLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LastDateReportSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastDateReportLabel)))
                    .addComponent(GenerateReportButton))
                .addGap(18, 18, 18)
                .addComponent(ReportScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );

        AdminTabbedPanel.addTab("Reportes", ReportAdminPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminTabbedPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(593, Short.MAX_VALUE)
                        .addComponent(ExitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(AdminTabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        MainController.setVisibleAdminView(false);
    }//GEN-LAST:event_ExitButtonActionPerformed

private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
    EmployeeList.removeAll();
    String searchText = ConsultEmployeeTextField.getText();
    if (searchText.isEmpty()) {
        EmployeeList.setModel(AdministrateEmployeeController.TotalSearchOfEmployees());
    } else {
        EmployeeList.setModel(AdministrateEmployeeController.SearchOfEmployees(searchText));
    }
}//GEN-LAST:event_SearchButtonActionPerformed

    public void showMessage(String title, String message, int messageType) {
        JOptionPane.showMessageDialog(rootPane, message, title, messageType);
        PlateExampleTextField.setText("");
        IdentifierPlateTextField.setText("");
        IdentifierPlateTextField.requestFocus();
    }

    public int showOptionMessage(String message) {
        int option = JOptionPane.showConfirmDialog(rootPane, message);
        return option;
    }

private void EmployeeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_EmployeeListValueChanged
    int emp = EmployeeList.getSelectedIndex();
    if (emp >= 0) {
        Employee e = AdministrateEmployeeController.getEmployeeListSearch().get(emp);
        AdministrateEmployeeController.setTempEmployee(e);
        IdEmployeeTextField.setText(String.valueOf(e.getId()));
        NameEmployeeTextField.setText(e.getName());
        LastNameEmployeeTextField.setText(e.getLastName());
        DocumentEmployeeTextField.setText(e.getDocument());
        isAdminEmployeeCheckBox.setSelected(e.isAdministrator());
    }
}//GEN-LAST:event_EmployeeListValueChanged

private void SavePlateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavePlateButtonActionPerformed
    MainController.saveNewVehicleType(IdentifierPlateTextField.getText(), PlateExampleTextField.getText());
}//GEN-LAST:event_SavePlateButtonActionPerformed

    public void setPlatesTableModel(TableModel dataModel) {
        PlatesTable.setModel(dataModel);
    }

    public void updatePlatesTable() {
        PlatesTable.updateUI();
    }

    public void setVehicleTypeComboBoxModel(ComboBoxModel aModel) {
        VehicleTypeComboBox.setModel(aModel);
    }

    public void updateVehicleTypeComboBox() {
        VehicleTypeComboBox.updateUI();
    }

private void PlateExampleTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PlateExampleTextFieldKeyPressed
    PlateExampleTextField.setText(PlateExampleTextField.getText().toUpperCase());

}//GEN-LAST:event_PlateExampleTextFieldKeyPressed

private void PlateExampleTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PlateExampleTextFieldKeyReleased
    PlateExampleTextField.setText(PlateExampleTextField.getText().toUpperCase());

}//GEN-LAST:event_PlateExampleTextFieldKeyReleased

private void SavePlateButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SavePlateButtonFocusGained
    PlateExampleTextField.requestFocus();
}//GEN-LAST:event_SavePlateButtonFocusGained

private void GenerateReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReportButtonActionPerformed
    int confirm = JOptionPane.showConfirmDialog(rootPane, "¿Desea guardar este reporte en el sistema?");
    if (confirm == 0) {
        //codigo para guardar el reporte en el sistema
    } else {
        //codigo solo para generar reporte
    }
}//GEN-LAST:event_GenerateReportButtonActionPerformed

    private void AdminTabbedPanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AdminTabbedPanelFocusGained
        VehicleTypeComboBox.setModel(AdministrateBandRates.AllVehicleTypes());
        VehicleTypeComboBox.updateUI();
        PlatesTable.setModel(AdministrateVehicleTypeController.TotalSearchOfVehicles());
        PlatesTable.updateUI();
        EmployeeList.setModel(AdministrateEmployeeController.TotalSearchOfEmployees());
        EmployeeList.updateUI();
        String id = (String) VehicleTypeComboBox.getSelectedItem();
        RatesTable.setModel(AdministrateBandRates.getModelTable(AdministrateBandRates.getVehicleTypeSelected(id)));
        RatesTable.updateUI();
    }//GEN-LAST:event_AdminTabbedPanelFocusGained

    private void CreateEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateEmployeeButtonActionPerformed
        if (flag) {
            CreateEmployeeButton.setText("Guardar Empleado");
            IdEmployeeTextField.setText("ID según BD"); // Lo trae de la DB
            this.setEnabledEmp();
            flag = false;
        } else if (JOptionPane.showConfirmDialog(null,
                ("¿Esta seguro de crear al empleado " + NameEmployeeTextField.getText() + "?"))
                == JOptionPane.OK_OPTION) {
            CreateEmployeeButton.setText("Crear Empleado");
            // Aquí lo crea
            this.setEnabledEmp();
            this.setNullEmp();
            flag = true;
        }
    }//GEN-LAST:event_CreateEmployeeButtonActionPerformed

private void SaveRateChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveRateChangesButtonActionPerformed
    if (RatesTable.isEditing()) {
        RatesTable.getCellEditor().stopCellEditing();
    }
    String id = (String) VehicleTypeComboBox.getSelectedItem();
    for (int i=0;i<RatesTable.getRowCount();i++){
        AdministrateBandRates.rowIsEdited(i, 
                String.valueOf(RatesTable.getValueAt(i, 1)),
                String.valueOf(RatesTable.getValueAt(i, 2)),
                String.valueOf(RatesTable.getValueAt(i, 3)),
                String.valueOf(RatesTable.getValueAt(i, 4)),
                AdministrateBandRates.getVehicleTypeSelected(id));
    }
    
    RatesTable.setModel(AdministrateBandRates.getModelTable(AdministrateBandRates.getVehicleTypeSelected(id)));
    RatesTable.updateUI();
    
}//GEN-LAST:event_SaveRateChangesButtonActionPerformed

private void VehicleTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_VehicleTypeComboBoxItemStateChanged
    String id = (String) VehicleTypeComboBox.getSelectedItem();
    RatesTable.setModel(AdministrateBandRates.getModelTable(AdministrateBandRates.getVehicleTypeSelected(id)));
    RatesTable.updateUI();
}//GEN-LAST:event_VehicleTypeComboBoxItemStateChanged
    private boolean flag = true;

    private void setEnabledEmp() {
        NameEmployeeTextField.setEnabled(flag);
        LastNameEmployeeTextField.setEnabled(flag);
        DocumentEmployeeTextField.setEnabled(flag);
        UserTextField.setEnabled(flag);
        PasswordField.setEnabled(flag);
        isAdminEmployeeCheckBox.setEnabled(flag);
        isActiveEmployeeCheckBox.setEnabled(flag);
    }

    private void setNullEmp() {
        IdEmployeeTextField.setText(null);
        NameEmployeeTextField.setText(null);
        LastNameEmployeeTextField.setText(null);
        DocumentEmployeeTextField.setText(null);
        UserTextField.setText(null);
        PasswordField.setText(null);
        isActiveEmployeeCheckBox.setSelected(false);
        isAdminEmployeeCheckBox.setSelected(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressParkwayLabel;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JTabbedPane AdminTabbedPanel;
    private javax.swing.JTextField ConsultEmployeeTextField;
    private javax.swing.JButton CreateEmployeeButton;
    private javax.swing.JLabel DocumentEmployeeLabel;
    private javax.swing.JTextField DocumentEmployeeTextField;
    private javax.swing.JPanel EmployeeAdminPanel;
    private javax.swing.JList EmployeeList;
    private javax.swing.JLabel EmployeeListLabel;
    private javax.swing.JScrollPane EmployeeListScroll;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton GenerateReportButton;
    private javax.swing.JLabel IdEmployeeLabel;
    private javax.swing.JTextField IdEmployeeTextField;
    private javax.swing.JTextField IdentifierPlateTextField;
    private javax.swing.JLabel LastDateReportLabel;
    private javax.swing.JSpinner LastDateReportSpinner;
    private javax.swing.JLabel LastNameEmployeeLabel;
    private javax.swing.JTextField LastNameEmployeeTextField;
    private javax.swing.JLabel MaxCapacityLabel;
    private javax.swing.JTextField MaxCapacityTextField;
    private javax.swing.JLabel NITParkwayLabel;
    private javax.swing.JTextField NITParkwayTextField;
    private javax.swing.JLabel NameEmployeeLabel;
    private javax.swing.JTextField NameEmployeeTextField;
    private javax.swing.JLabel NameParkwayLabel;
    private javax.swing.JTextField NameParkwayTextField;
    private javax.swing.JPanel ParkwayAdminPanel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPanel PlateAdmin;
    private javax.swing.JTextField PlateExampleTextField;
    private javax.swing.JLabel PlateSampleLabel;
    private javax.swing.JTable PlatesTable;
    private javax.swing.JPanel RateAdminPanel;
    private javax.swing.JScrollPane RatesScroll;
    private javax.swing.JTable RatesTable;
    private javax.swing.JPanel ReportAdminPanel;
    private javax.swing.JScrollPane ReportScroll;
    private javax.swing.JTable ReportTable;
    private javax.swing.JComboBox ReportTypeCombo;
    private javax.swing.JLabel ReportTypeLabel;
    private javax.swing.JButton SaveParkwayChangesButton;
    private javax.swing.JButton SavePlateButton;
    private javax.swing.JButton SaveRateChangesButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel SearchEmployeeLabel;
    private javax.swing.JLabel StartDateReportLabel;
    private javax.swing.JSpinner StartDateReportSpinner;
    private javax.swing.JLabel TelephoneParkwayLabel;
    private javax.swing.JTextField TelephoneTextField;
    private javax.swing.JButton UpdateEmployeeButton;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField UserTextField;
    private javax.swing.JComboBox VehicleTypeComboBox;
    private javax.swing.JLabel VehicleTypeLabel;
    private javax.swing.JLabel VehicleTypeNameLabel;
    private javax.swing.JScrollPane VehicleTypeScroll;
    private javax.swing.JCheckBox isActiveEmployeeCheckBox;
    private javax.swing.JCheckBox isAdminEmployeeCheckBox;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
