/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdministrationView.java
 *
 * Created on 06-oct-2011, 13:08:24
 */
package view;

import DAO.exceptions.PreexistingEntityException;
import Entity.Employee;
import Entity.VehicleType;
import controller.Administration.AdministrateEmployeeController;
import controller.Administration.AdministrateRates;
import controller.Administration.AdministrateVehicleTypeController;
import controller.Administration.AdministrationController;
import controller.MainController;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author r4wd3r
 */
public class AdministrationView extends javax.swing.JFrame {

    /** Creates new form AdministrationView */
    public AdministrationView() {
        initComponents();
        

    }

    public JList getEmployeeList() {
        return EmployeeList;
    }

    public void setEmployeeList(JList EmployeeList) {
        this.EmployeeList = EmployeeList;
    }
    
    public JTable getPlatesTable() {
        return PlatesTable;
    }

    public void setPlatesTable(JTable PlatesTable) {
        this.PlatesTable = PlatesTable;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        AdminTabbedPanel = new javax.swing.JTabbedPane();
        ParkwayAdminPanel = new javax.swing.JPanel();
        NameParkwayTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NameParkwayTextField1 = new javax.swing.JTextField();
        NameParkwayTextField2 = new javax.swing.JTextField();
        NameParkwayTextField3 = new javax.swing.JTextField();
        NameParkwayTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        EmployeeAdminPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        IdEmployeeTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NameEmployeeTextField = new javax.swing.JTextField();
        LastNameEmployeeTextField = new javax.swing.JTextField();
        DocumentEmployeeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        isAdminEmployeeCheckBox = new javax.swing.JCheckBox();
        CreateEmployeeButton = new javax.swing.JButton();
        UpdateEmployeeButton = new javax.swing.JButton();
        DeleteEmployeeButton = new javax.swing.JButton();
        ConsultEmployeeTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        RateAdminPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        VehicleTypeComboBox = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        PlateAdmin = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        PlateExampleTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        savePlateButton = new javax.swing.JButton();
        IdentifierPlateTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        PlatesTable = new javax.swing.JTable();
        ReportAdminPanel = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        GenerateReportButton = new javax.swing.JButton();

        jLabel12.setText("jLabel12");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ExitButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        ExitButton.setText("Cerrar");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        AdminTabbedPanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AdminTabbedPanelFocusGained(evt);
            }
        });

        ParkwayAdminPanel.setBackground(new java.awt.Color(254, 254, 254));

        jLabel6.setText("Nombre:");

        jLabel7.setText("Dirección:");

        jLabel8.setText("NIT:");

        jLabel9.setText("Teléfono:");

        jLabel10.setText("Capacidad Máxima:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Database.png"))); // NOI18N
        jButton1.setText("Guardar Cambios");

        javax.swing.GroupLayout ParkwayAdminPanelLayout = new javax.swing.GroupLayout(ParkwayAdminPanel);
        ParkwayAdminPanel.setLayout(ParkwayAdminPanelLayout);
        ParkwayAdminPanelLayout.setHorizontalGroup(
            ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParkwayAdminPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(35, 35, 35)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameParkwayTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ParkwayAdminPanelLayout.createSequentialGroup()
                        .addComponent(NameParkwayTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(jButton1))
                    .addComponent(NameParkwayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameParkwayTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameParkwayTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ParkwayAdminPanelLayout.setVerticalGroup(
            ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParkwayAdminPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NameParkwayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(NameParkwayTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameParkwayTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jButton1))
                .addGap(12, 12, 12)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(NameParkwayTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(NameParkwayTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        AdminTabbedPanel.addTab("Administrar Parqueadero", ParkwayAdminPanel);

        EmployeeAdminPanel.setBackground(new java.awt.Color(254, 254, 254));

        EmployeeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                EmployeeListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(EmployeeList);

        jLabel1.setText("Lista de Empleados:");

        IdEmployeeTextField.setEditable(false);

        jLabel2.setText("ID:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellidos:");

        jLabel5.setText("Documento:");

        isAdminEmployeeCheckBox.setText("Administrador");

        CreateEmployeeButton.setText("Crear Operario");

        UpdateEmployeeButton.setText("Actualizar Operario");

        DeleteEmployeeButton.setText("Eliminar Operario");

        jLabel11.setText("Buscar:");

        SearchButton.setText("Buscar");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmployeeAdminPanelLayout = new javax.swing.GroupLayout(EmployeeAdminPanel);
        EmployeeAdminPanel.setLayout(EmployeeAdminPanelLayout);
        EmployeeAdminPanelLayout.setHorizontalGroup(
            EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(51, 51, 51)
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DocumentEmployeeTextField)
                                    .addComponent(IdEmployeeTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NameEmployeeTextField)
                                    .addComponent(LastNameEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DeleteEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CreateEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UpdateEmployeeButton)))
                            .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(isAdminEmployeeCheckBox))))
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeAdminPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsultEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchButton)
                        .addGap(248, 248, 248)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmployeeAdminPanelLayout.setVerticalGroup(
            EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(SearchButton))
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IdEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(CreateEmployeeButton))
                        .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NameEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LastNameEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DocumentEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(DeleteEmployeeButton))
                                .addGap(18, 18, 18)
                                .addComponent(isAdminEmployeeCheckBox))
                            .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(UpdateEmployeeButton))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        AdminTabbedPanel.addTab("Administrar Operario", EmployeeAdminPanel);

        RateAdminPanel.setBackground(new java.awt.Color(254, 254, 254));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Identificador", "Desde (Minuto)", "Hasta (Minuto)", "Fracción", "Valor Fracción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable4);

        jLabel18.setText("Tipo de Vehículo:");

        new javax.swing.DefaultComboBoxModel(new String[] { "-" });

        jButton3.setText("Guardar cambios");

        javax.swing.GroupLayout RateAdminPanelLayout = new javax.swing.GroupLayout(RateAdminPanel);
        RateAdminPanel.setLayout(RateAdminPanelLayout);
        RateAdminPanelLayout.setHorizontalGroup(
            RateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RateAdminPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel18)
                .addGap(52, 52, 52)
                .addComponent(VehicleTypeComboBox, 0, 151, Short.MAX_VALUE)
                .addGap(147, 147, 147)
                .addComponent(jButton3)
                .addGap(86, 86, 86))
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );
        RateAdminPanelLayout.setVerticalGroup(
            RateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RateAdminPanelLayout.createSequentialGroup()
                .addGroup(RateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RateAdminPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(RateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(VehicleTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RateAdminPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        AdminTabbedPanel.addTab("Administrar Tarifas", RateAdminPanel);

        PlateAdmin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Ejemplo de placa:");

        PlateExampleTextField.setFont(new java.awt.Font("Tahoma", 0, 24));
        PlateExampleTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PlateExampleTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PlateExampleTextFieldKeyReleased(evt);
            }
        });

        jLabel14.setText("Nombre del tipo de vehiculo:");

        savePlateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Database.png"))); // NOI18N
        savePlateButton.setText("Guardar Placa");
        savePlateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePlateButtonActionPerformed(evt);
            }
        });
        savePlateButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                savePlateButtonFocusGained(evt);
            }
        });

        PlatesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Identificador", "Tipo de Vehiculo", "Ejemplo de Placa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(PlatesTable);
        PlatesTable.getColumnModel().getColumn(0).setMinWidth(20);
        PlatesTable.getColumnModel().getColumn(0).setPreferredWidth(80);
        PlatesTable.getColumnModel().getColumn(0).setMaxWidth(150);

        javax.swing.GroupLayout PlateAdminLayout = new javax.swing.GroupLayout(PlateAdmin);
        PlateAdmin.setLayout(PlateAdminLayout);
        PlateAdminLayout.setHorizontalGroup(
            PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlateAdminLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlateAdminLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(PlateAdminLayout.createSequentialGroup()
                        .addGroup(PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlateExampleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(IdentifierPlateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addComponent(savePlateButton)
                        .addGap(58, 58, 58))))
        );

        PlateAdminLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {IdentifierPlateTextField, PlateExampleTextField});

        PlateAdminLayout.setVerticalGroup(
            PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlateAdminLayout.createSequentialGroup()
                .addGroup(PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlateAdminLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(IdentifierPlateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PlateAdminLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(25, 25, 25))
                            .addGroup(PlateAdminLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(PlateExampleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44))
                    .addGroup(PlateAdminLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(savePlateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        AdminTabbedPanel.addTab("Administrar Placas", PlateAdmin);

        ReportAdminPanel.setBackground(new java.awt.Color(254, 254, 254));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText("Tipo de Reporte:");

        jLabel16.setText("Fecha de Inicio de reporte:");

        jLabel17.setText("Fecha de Terminacion de reporte:");

        jSpinner3.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));

        jSpinner6.setModel(new javax.swing.SpinnerDateModel());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        GenerateReportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Stationery.png"))); // NOI18N
        GenerateReportButton.setText("Generar");
        GenerateReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReportAdminPanelLayout = new javax.swing.GroupLayout(ReportAdminPanel);
        ReportAdminPanel.setLayout(ReportAdminPanelLayout);
        ReportAdminPanelLayout.setHorizontalGroup(
            ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportAdminPanelLayout.createSequentialGroup()
                .addGroup(ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReportAdminPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSpinner3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 203, Short.MAX_VALUE))
                            .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(GenerateReportButton))
                    .addGroup(ReportAdminPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ReportAdminPanelLayout.setVerticalGroup(
            ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportAdminPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ReportAdminPanelLayout.createSequentialGroup()
                        .addGroup(ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addComponent(GenerateReportButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        AdminTabbedPanel.addTab("Reportes", ReportAdminPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminTabbedPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(593, Short.MAX_VALUE)
                        .addComponent(ExitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(AdminTabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        MainController.setVisibleAdminView(false);
    }//GEN-LAST:event_ExitButtonActionPerformed

private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
    EmployeeList.removeAll();
    String searchText = ConsultEmployeeTextField.getText();
    if (searchText.isEmpty()) {
        EmployeeList.setModel(AdministrateEmployeeController.TotalSearchOfEmployees());
    } else {
        EmployeeList.setModel(AdministrateEmployeeController.SearchOfEmployees(searchText));
    }
}//GEN-LAST:event_SearchButtonActionPerformed

private void EmployeeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_EmployeeListValueChanged
    int emp = EmployeeList.getSelectedIndex();
    if (emp >= 0) {
        Employee e = AdministrateEmployeeController.getEmployeeListSearch().get(emp);
        AdministrateEmployeeController.setTempEmployee(e);
        IdEmployeeTextField.setText(String.valueOf(e.getId()));
        NameEmployeeTextField.setText(e.getName());
        LastNameEmployeeTextField.setText(e.getLastName());
        DocumentEmployeeTextField.setText(e.getDocument());
        isAdminEmployeeCheckBox.setSelected(e.isAdministrator());
    }
}//GEN-LAST:event_EmployeeListValueChanged

private void savePlateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePlateButtonActionPerformed
    if (IdentifierPlateTextField.getText().isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "Nombre de Vehiculo vacio, por favor ingrese un nombre descriptivo",
                "Error", JOptionPane.WARNING_MESSAGE);
        IdentifierPlateTextField.requestFocus();
    } else if (PlateExampleTextField.getText().isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "Ejemplo de placa vacio, por favor ingrese un ejemplo de la placa",
                "Error", JOptionPane.WARNING_MESSAGE);
        PlateExampleTextField.requestFocus();
    } else {
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Esta seguro crear un nuevo tipo de placa? ("
                + IdentifierPlateTextField.getText() + " )");
        if (confirm == 0) {
            String state = AdministrateVehicleTypeController.SavePlate(IdentifierPlateTextField.getText(), PlateExampleTextField.getText());
            if (state == "Failure") {
                JOptionPane.showMessageDialog(rootPane, "Solo se permiten valores alfa-numericos en la placa",
                        "Error", JOptionPane.WARNING_MESSAGE);
                PlateExampleTextField.setText("");
                PlateExampleTextField.requestFocus();
            } 
            else {
                JOptionPane.showMessageDialog(rootPane, "Se ha creado exitosamente el tipo de placa " + IdentifierPlateTextField.getText(),
                        "Se ha creado un nuevo tipo de placa", JOptionPane.INFORMATION_MESSAGE);
                PlatesTable.setModel(AdministrateVehicleTypeController.TotalSearchOfVehicles());
                PlatesTable.updateUI();
                VehicleTypeComboBox.setModel(AdministrateRates.AllVehicleTypes());
                VehicleTypeComboBox.updateUI();


            }
        }

    }
}//GEN-LAST:event_savePlateButtonActionPerformed

private void PlateExampleTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PlateExampleTextFieldKeyPressed
    PlateExampleTextField.setText(PlateExampleTextField.getText().toUpperCase());

}//GEN-LAST:event_PlateExampleTextFieldKeyPressed

private void PlateExampleTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PlateExampleTextFieldKeyReleased
    PlateExampleTextField.setText(PlateExampleTextField.getText().toUpperCase());

}//GEN-LAST:event_PlateExampleTextFieldKeyReleased

private void savePlateButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_savePlateButtonFocusGained
    PlateExampleTextField.requestFocus();
}//GEN-LAST:event_savePlateButtonFocusGained

private void GenerateReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReportButtonActionPerformed
    int confirm = JOptionPane.showConfirmDialog(rootPane, "¿Desea guardar este reporte en el sistema?");
        if (confirm == 0) {
            //codigo para guardar el reporte en el sistema
            } 
            else {
                //codigo solo para generar reporte

            }
}//GEN-LAST:event_GenerateReportButtonActionPerformed

    private void AdminTabbedPanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AdminTabbedPanelFocusGained
        VehicleTypeComboBox.setModel(AdministrateRates.AllVehicleTypes());
        VehicleTypeComboBox.updateUI();
        PlatesTable.setModel(AdministrateVehicleTypeController.TotalSearchOfVehicles());
        PlatesTable.updateUI();
        EmployeeList.setModel(AdministrateEmployeeController.TotalSearchOfEmployees());
        EmployeeList.updateUI();
    }//GEN-LAST:event_AdminTabbedPanelFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AdminTabbedPanel;
    private javax.swing.JTextField ConsultEmployeeTextField;
    private javax.swing.JButton CreateEmployeeButton;
    private javax.swing.JButton DeleteEmployeeButton;
    private javax.swing.JTextField DocumentEmployeeTextField;
    private javax.swing.JPanel EmployeeAdminPanel;
    private javax.swing.JList EmployeeList;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton GenerateReportButton;
    private javax.swing.JTextField IdEmployeeTextField;
    private javax.swing.JTextField IdentifierPlateTextField;
    private javax.swing.JTextField LastNameEmployeeTextField;
    private javax.swing.JTextField NameEmployeeTextField;
    private javax.swing.JTextField NameParkwayTextField;
    private javax.swing.JTextField NameParkwayTextField1;
    private javax.swing.JTextField NameParkwayTextField2;
    private javax.swing.JTextField NameParkwayTextField3;
    private javax.swing.JTextField NameParkwayTextField4;
    private javax.swing.JPanel ParkwayAdminPanel;
    private javax.swing.JPanel PlateAdmin;
    private javax.swing.JTextField PlateExampleTextField;
    private javax.swing.JTable PlatesTable;
    private javax.swing.JPanel RateAdminPanel;
    private javax.swing.JPanel ReportAdminPanel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton UpdateEmployeeButton;
    private javax.swing.JComboBox VehicleTypeComboBox;
    private javax.swing.JCheckBox isAdminEmployeeCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton savePlateButton;
    // End of variables declaration//GEN-END:variables
}
