/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor
 */

/*
 * AdministrationView.java
 *
 * Created on 06-oct-2011, 13:08:24
 */
package view;

import DAO.EmployeeJpaController;
import Entity.Employee;
import controller.Administration.AdministrateEmployeeController;
import controller.Administration.AdministrateBandRates;
import controller.Administration.AdministrateVehicleTypeController;
import controller.Administration.EmployeeManagementController;
import controller.MainController;
import javax.swing.ComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author Grupo E
 */
public class AdministrationView extends javax.swing.JFrame {

    /** Creates new form AdministrationView */
    public AdministrationView() {
        ImageIcon img=new ImageIcon("src/images/parking1.gif"); 
        setIconImage(img.getImage()); 
        initComponents();
    }

    public JList getEmployeeList() {
        return EmployeeList;
    }

    public void setEmployeeList(JList EmployeeList) {
        this.EmployeeList = EmployeeList;
    }

    public JTable getPlatesTable() {
        return PlatesTable;
    }

    public void setPlatesTable(JTable PlatesTable) {
        this.PlatesTable = PlatesTable;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        AdminTabbedPanel = new javax.swing.JTabbedPane();
        ParkwayAdminPanel = new javax.swing.JPanel();
        NameParkwayTextField = new javax.swing.JTextField();
        NameParkwayLabel = new javax.swing.JLabel();
        AddressTextField = new javax.swing.JTextField();
        TelephoneTextField = new javax.swing.JTextField();
        NITParkwayTextField = new javax.swing.JTextField();
        MaxCapacityTextField = new javax.swing.JTextField();
        AddressParkwayLabel = new javax.swing.JLabel();
        NITParkwayLabel = new javax.swing.JLabel();
        TelephoneParkwayLabel = new javax.swing.JLabel();
        MaxCapacityLabel = new javax.swing.JLabel();
        SaveParkwayChangesButton = new javax.swing.JButton();
        EmployeeAdminPanel = new javax.swing.JPanel();
        EmployeeListScroll = new javax.swing.JScrollPane();
        EmployeeList = new javax.swing.JList();
        EmployeeListLabel = new javax.swing.JLabel();
        IdEmployeeTextField = new javax.swing.JTextField();
        IdEmployeeLabel = new javax.swing.JLabel();
        NameEmployeeTextField = new javax.swing.JTextField();
        LastNameEmployeeTextField = new javax.swing.JTextField();
        DocumentEmployeeTextField = new javax.swing.JTextField();
        NameEmployeeLabel = new javax.swing.JLabel();
        LastNameEmployeeLabel = new javax.swing.JLabel();
        DocumentEmployeeLabel = new javax.swing.JLabel();
        isAdminEmployeeCheckBox = new javax.swing.JCheckBox();
        CreateEmployeeButton = new javax.swing.JButton();
        UpdateEmployeeButton = new javax.swing.JButton();
        ConsultEmployeeTextField = new javax.swing.JTextField();
        SearchEmployeeLabel = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        UserLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UserTextField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        isActiveEmployeeCheckBox = new javax.swing.JCheckBox();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        AdministrateVehicles = new javax.swing.JPanel();
        SubPanel = new javax.swing.JTabbedPane();
        PlateAdmin = new javax.swing.JPanel();
        PlateSampleLabel = new javax.swing.JLabel();
        PlateExampleTextField = new javax.swing.JTextField();
        VehicleTypeNameLabel = new javax.swing.JLabel();
        SavePlateButton = new javax.swing.JButton();
        IdentifierPlateTextField = new javax.swing.JTextField();
        VehicleTypeScroll = new javax.swing.JScrollPane();
        PlatesTable = new javax.swing.JTable();
        RateAdminPanel = new javax.swing.JPanel();
        RatesScroll = new javax.swing.JScrollPane();
        RatesTable = new javax.swing.JTable();
        VehicleTypeLabel = new javax.swing.JLabel();
        VehicleTypeComboBox = new javax.swing.JComboBox();
        SaveRateChangesButton = new javax.swing.JButton();
        DeleteLastRate = new javax.swing.JButton();
        ReportAdminPanel = new javax.swing.JPanel();
        ReportsTabbedPanel = new javax.swing.JTabbedPane();
        PartialReportPanel = new javax.swing.JPanel();
        PartialReportDateTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        PartialReportTable = new javax.swing.JTable();
        PartialReportTotalTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PartialReportPrintButton = new javax.swing.JButton();
        PartialReportGenerateButton = new javax.swing.JButton();
        PartialReportSearchButton = new javax.swing.JButton();
        CustomReportPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CustomReportFromTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        CustomReportTable = new javax.swing.JTable();
        CustomReportTotalTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CustomReportPrintButton = new javax.swing.JButton();
        CustomReportGenerateButton = new javax.swing.JButton();
        CustomReportToTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PartialReportSearchButton1 = new javax.swing.JButton();
        PartialReportSearchButton2 = new javax.swing.JButton();

        jLabel12.setText("jLabel12");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administración de ParkQuick");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        ExitButton.setText("Cerrar");
        ExitButton.setToolTipText("Terminar la configuración.");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        AdminTabbedPanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AdminTabbedPanelFocusGained(evt);
            }
        });

        ParkwayAdminPanel.setBackground(new java.awt.Color(254, 254, 254));

        NameParkwayTextField.setEditable(false);
        NameParkwayTextField.setToolTipText("Ingrese el nombre de su negocio.");

        NameParkwayLabel.setText("Nombre:");

        AddressTextField.setEditable(false);
        AddressTextField.setToolTipText("Ingrese la dirección de su negocio.");

        TelephoneTextField.setEditable(false);
        TelephoneTextField.setToolTipText("Ingrese el teléfono de su negocio.");

        NITParkwayTextField.setEditable(false);
        NITParkwayTextField.setToolTipText("Ingrese el número del NIT de su negocio.");

        MaxCapacityTextField.setEditable(false);
        MaxCapacityTextField.setToolTipText("Ingrese la capacidad máxima de su negocio.");

        AddressParkwayLabel.setText("Dirección:");

        NITParkwayLabel.setText("NIT:");

        TelephoneParkwayLabel.setText("Teléfono:");

        MaxCapacityLabel.setText("Capacidad Máxima:");

        SaveParkwayChangesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Database.png"))); // NOI18N
        SaveParkwayChangesButton.setText("Cambiar Datos");
        SaveParkwayChangesButton.setToolTipText("Cambia los datos de la base de datos según los cambios.");
        SaveParkwayChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveParkwayChangesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ParkwayAdminPanelLayout = new javax.swing.GroupLayout(ParkwayAdminPanel);
        ParkwayAdminPanel.setLayout(ParkwayAdminPanelLayout);
        ParkwayAdminPanelLayout.setHorizontalGroup(
            ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParkwayAdminPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameParkwayLabel)
                    .addComponent(NITParkwayLabel)
                    .addComponent(MaxCapacityLabel)
                    .addComponent(AddressParkwayLabel)
                    .addComponent(TelephoneParkwayLabel))
                .addGap(35, 35, 35)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TelephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ParkwayAdminPanelLayout.createSequentialGroup()
                        .addComponent(NITParkwayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(SaveParkwayChangesButton))
                    .addComponent(NameParkwayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaxCapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        ParkwayAdminPanelLayout.setVerticalGroup(
            ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParkwayAdminPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameParkwayLabel)
                    .addComponent(NameParkwayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddressParkwayLabel)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NITParkwayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NITParkwayLabel)
                    .addComponent(SaveParkwayChangesButton))
                .addGap(12, 12, 12)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelephoneParkwayLabel)
                    .addComponent(TelephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(ParkwayAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaxCapacityLabel)
                    .addComponent(MaxCapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        AdminTabbedPanel.addTab("Administrar Parqueadero", ParkwayAdminPanel);

        EmployeeAdminPanel.setBackground(new java.awt.Color(254, 254, 254));

        EmployeeListScroll.setToolTipText("Empleados registrados en el sistema.");

        EmployeeList.setToolTipText("Empleados registrados en el sistema.");
        EmployeeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeListMouseClicked(evt);
            }
        });
        EmployeeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                EmployeeListValueChanged(evt);
            }
        });
        EmployeeListScroll.setViewportView(EmployeeList);

        EmployeeListLabel.setText("Lista de Empleados:");

        IdEmployeeTextField.setEditable(false);
        IdEmployeeTextField.setToolTipText("Identificador de empleado (No editable)");

        IdEmployeeLabel.setText("ID:");

        NameEmployeeTextField.setToolTipText("Nombre empleado.");
        NameEmployeeTextField.setEnabled(false);

        LastNameEmployeeTextField.setToolTipText("Apellido empleado.");
        LastNameEmployeeTextField.setEnabled(false);

        DocumentEmployeeTextField.setToolTipText("Documento empleado.");
        DocumentEmployeeTextField.setEnabled(false);

        NameEmployeeLabel.setText("Nombre:");

        LastNameEmployeeLabel.setText("Apellidos:");

        DocumentEmployeeLabel.setText("Documento:");

        isAdminEmployeeCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        isAdminEmployeeCheckBox.setText("Administrador");
        isAdminEmployeeCheckBox.setToolTipText("Seleccione aquí para dar permisos de Administador al empleado cuya información aparece arriba.");
        isAdminEmployeeCheckBox.setEnabled(false);

        CreateEmployeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit.png"))); // NOI18N
        CreateEmployeeButton.setText("Crear Empleado");
        CreateEmployeeButton.setToolTipText("Crear un nuevo empleado de acuerdo a lo ingresado.");
        CreateEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateEmployeeButtonActionPerformed(evt);
            }
        });

        UpdateEmployeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Refresh.png"))); // NOI18N
        UpdateEmployeeButton.setText("Actualizar Empleado");
        UpdateEmployeeButton.setToolTipText("Actualizar un empleado existente con la información ingresada.");
        UpdateEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmployeeButtonActionPerformed(evt);
            }
        });

        ConsultEmployeeTextField.setToolTipText("Ingrese el código del empleado que desee buscar.");

        SearchEmployeeLabel.setText("Buscar:");

        SearchButton.setText("Buscar");
        SearchButton.setToolTipText("Buscar empleado en el sistema, si deja vacío el espacio a su izquierda buscará todos los empleados.");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        UserLabel.setText("Usuario:");

        PasswordLabel.setText("Contraseña:");

        UserTextField.setToolTipText("Nombre con que el empleado accederá al sistema.");
        UserTextField.setEnabled(false);

        PasswordField.setToolTipText("Contraseña con al que el empleado accederá al sistema.");
        PasswordField.setEnabled(false);

        isActiveEmployeeCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        isActiveEmployeeCheckBox.setText("Activo");
        isActiveEmployeeCheckBox.setToolTipText("Seleccione aquí para permitir al empleado acceso al sistema.");
        isActiveEmployeeCheckBox.setEnabled(false);

        ConfirmPasswordField.setEnabled(false);

        ConfirmPasswordLabel.setText("Confirmar Contraseña:");

        javax.swing.GroupLayout EmployeeAdminPanelLayout = new javax.swing.GroupLayout(EmployeeAdminPanel);
        EmployeeAdminPanel.setLayout(EmployeeAdminPanelLayout);
        EmployeeAdminPanelLayout.setHorizontalGroup(
            EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeAdminPanelLayout.createSequentialGroup()
                        .addGap(557, 557, 557)
                        .addComponent(CreateEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeAdminPanelLayout.createSequentialGroup()
                        .addContainerGap(665, Short.MAX_VALUE)
                        .addComponent(UpdateEmployeeButton))
                    .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeAdminPanelLayout.createSequentialGroup()
                                .addComponent(SearchEmployeeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ConsultEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SearchButton))
                            .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                                .addComponent(EmployeeListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IdEmployeeLabel)
                                    .addComponent(NameEmployeeLabel)
                                    .addComponent(LastNameEmployeeLabel)
                                    .addComponent(DocumentEmployeeLabel)
                                    .addComponent(UserLabel)
                                    .addComponent(PasswordLabel)
                                    .addComponent(ConfirmPasswordLabel)
                                    .addComponent(isAdminEmployeeCheckBox))
                                .addGap(49, 49, 49)
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ConfirmPasswordField)
                                        .addComponent(LastNameEmployeeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                        .addComponent(UserTextField)
                                        .addComponent(DocumentEmployeeTextField)
                                        .addComponent(NameEmployeeTextField)
                                        .addComponent(IdEmployeeTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                                    .addComponent(isActiveEmployeeCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(EmployeeListLabel))))
                .addContainerGap())
        );

        EmployeeAdminPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CreateEmployeeButton, UpdateEmployeeButton});

        EmployeeAdminPanelLayout.setVerticalGroup(
            EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EmployeeAdminPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConsultEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchEmployeeLabel)
                            .addComponent(SearchButton))
                        .addGap(28, 28, 28)
                        .addComponent(EmployeeListLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmployeeAdminPanelLayout.createSequentialGroup()
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(IdEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IdEmployeeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NameEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameEmployeeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LastNameEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LastNameEmployeeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DocumentEmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DocumentEmployeeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(UserLabel)
                                    .addComponent(UserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PasswordLabel)
                                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ConfirmPasswordLabel)))
                            .addComponent(EmployeeListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EmployeeAdminPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(CreateEmployeeButton)
                        .addGap(46, 46, 46)
                        .addComponent(UpdateEmployeeButton)))
                .addGap(18, 18, 18)
                .addGroup(EmployeeAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isAdminEmployeeCheckBox)
                    .addComponent(isActiveEmployeeCheckBox))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        AdminTabbedPanel.addTab("Administrar Empleados", EmployeeAdminPanel);

        PlateAdmin.setBackground(new java.awt.Color(255, 255, 255));

        PlateSampleLabel.setText("Ejemplo de placa:");

        PlateExampleTextField.setFont(new java.awt.Font("Tahoma", 0, 24));
        PlateExampleTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PlateExampleTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PlateExampleTextFieldKeyReleased(evt);
            }
        });

        VehicleTypeNameLabel.setText("Nombre del tipo de vehículo:");

        SavePlateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Database.png"))); // NOI18N
        SavePlateButton.setText("Guardar Vehículo");
        SavePlateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavePlateButtonActionPerformed(evt);
            }
        });
        SavePlateButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SavePlateButtonFocusGained(evt);
            }
        });

        PlatesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Identificador", "Tipo de Vehiculo", "Ejemplo de Placa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        VehicleTypeScroll.setViewportView(PlatesTable);
        PlatesTable.getColumnModel().getColumn(0).setMinWidth(20);
        PlatesTable.getColumnModel().getColumn(0).setPreferredWidth(80);
        PlatesTable.getColumnModel().getColumn(0).setMaxWidth(150);

        javax.swing.GroupLayout PlateAdminLayout = new javax.swing.GroupLayout(PlateAdmin);
        PlateAdmin.setLayout(PlateAdminLayout);
        PlateAdminLayout.setHorizontalGroup(
            PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlateAdminLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VehicleTypeNameLabel)
                    .addComponent(PlateSampleLabel))
                .addGap(18, 18, 18)
                .addGroup(PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlateExampleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(IdentifierPlateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addComponent(SavePlateButton)
                .addGap(58, 58, 58))
            .addComponent(VehicleTypeScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
        );

        PlateAdminLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {IdentifierPlateTextField, PlateExampleTextField});

        PlateAdminLayout.setVerticalGroup(
            PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlateAdminLayout.createSequentialGroup()
                .addGroup(PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlateAdminLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VehicleTypeNameLabel)
                            .addComponent(IdentifierPlateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PlateAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PlateAdminLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(PlateSampleLabel)
                                .addGap(25, 25, 25))
                            .addGroup(PlateAdminLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(PlateExampleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44))
                    .addGroup(PlateAdminLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(SavePlateButton)))
                .addGap(11, 11, 11)
                .addComponent(VehicleTypeScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SubPanel.addTab("Administrar Vehículos", PlateAdmin);

        RateAdminPanel.setBackground(new java.awt.Color(254, 254, 254));

        RatesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Identificador", "Desde (Minuto)", "Hasta (Minuto)", "Fracción", "Valor Fracción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RatesScroll.setViewportView(RatesTable);

        VehicleTypeLabel.setText("Tipo de Vehículo:");

        new javax.swing.DefaultComboBoxModel(new String[] { "-" });
        VehicleTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                VehicleTypeComboBoxItemStateChanged(evt);
            }
        });

        SaveRateChangesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Floppy.png"))); // NOI18N
        SaveRateChangesButton.setText("Guardar cambios");
        SaveRateChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveRateChangesButtonActionPerformed(evt);
            }
        });

        DeleteLastRate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Undo.png"))); // NOI18N
        DeleteLastRate.setText("Borrar última regla");
        DeleteLastRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteLastRateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RateAdminPanelLayout = new javax.swing.GroupLayout(RateAdminPanel);
        RateAdminPanel.setLayout(RateAdminPanelLayout);
        RateAdminPanelLayout.setHorizontalGroup(
            RateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RateAdminPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(VehicleTypeLabel)
                .addGap(52, 52, 52)
                .addComponent(VehicleTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(SaveRateChangesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteLastRate)
                .addContainerGap())
            .addComponent(RatesScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
        );
        RateAdminPanelLayout.setVerticalGroup(
            RateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RateAdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RateAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehicleTypeLabel)
                    .addComponent(VehicleTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveRateChangesButton)
                    .addComponent(DeleteLastRate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RatesScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
        );

        SubPanel.addTab("Administrar Tarifas", RateAdminPanel);

        javax.swing.GroupLayout AdministrateVehiclesLayout = new javax.swing.GroupLayout(AdministrateVehicles);
        AdministrateVehicles.setLayout(AdministrateVehiclesLayout);
        AdministrateVehiclesLayout.setHorizontalGroup(
            AdministrateVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
        );
        AdministrateVehiclesLayout.setVerticalGroup(
            AdministrateVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        AdminTabbedPanel.addTab("Administrar Vehiculos y Tarifas", AdministrateVehicles);

        ReportAdminPanel.setBackground(new java.awt.Color(254, 254, 254));

        PartialReportPanel.setBackground(new java.awt.Color(255, 255, 255));

        PartialReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Factura", "Tiquete", "Hora", "Placa", "Costo"
            }
        ));
        jScrollPane1.setViewportView(PartialReportTable);
        PartialReportTable.getColumnModel().getColumn(1).setHeaderValue("Tiquete");

        jLabel2.setText("Fecha:");

        jLabel3.setText("Total Parcial:");

        PartialReportPrintButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Write.png"))); // NOI18N
        PartialReportPrintButton.setText("Imprimir Reporte");

        PartialReportGenerateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Folder.png"))); // NOI18N
        PartialReportGenerateButton.setText("Generar Reporte");
        PartialReportGenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartialReportGenerateButtonActionPerformed(evt);
            }
        });

        PartialReportSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Portfolio.png"))); // NOI18N
        PartialReportSearchButton.setText("   Buscar");

        javax.swing.GroupLayout PartialReportPanelLayout = new javax.swing.GroupLayout(PartialReportPanel);
        PartialReportPanel.setLayout(PartialReportPanelLayout);
        PartialReportPanelLayout.setHorizontalGroup(
            PartialReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PartialReportPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PartialReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PartialReportPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PartialReportTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PartialReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PartialReportPanelLayout.createSequentialGroup()
                            .addGap(193, 193, 193)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(PartialReportDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PartialReportSearchButton))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90)
                .addGroup(PartialReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PartialReportPrintButton, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(PartialReportGenerateButton))
                .addGap(76, 76, 76))
        );
        PartialReportPanelLayout.setVerticalGroup(
            PartialReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PartialReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PartialReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PartialReportDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(PartialReportSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PartialReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PartialReportPanelLayout.createSequentialGroup()
                        .addComponent(PartialReportGenerateButton)
                        .addGap(55, 55, 55)
                        .addComponent(PartialReportPrintButton))
                    .addGroup(PartialReportPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PartialReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PartialReportTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        ReportsTabbedPanel.addTab("Reporte Parcial Diario", PartialReportPanel);

        CustomReportPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Desde:");

        CustomReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Factura", "Fecha", "Hora", "Placa", "Costo"
            }
        ));
        jScrollPane2.setViewportView(CustomReportTable);

        jLabel5.setText("Total:");

        CustomReportPrintButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Write.png"))); // NOI18N
        CustomReportPrintButton.setText("Imprimir Reporte");

        CustomReportGenerateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Folder.png"))); // NOI18N
        CustomReportGenerateButton.setText("Generar Reporte");
        CustomReportGenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomReportGenerateButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Hasta:");

        PartialReportSearchButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Portfolio.png"))); // NOI18N
        PartialReportSearchButton1.setText("   Buscar");

        PartialReportSearchButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Portfolio.png"))); // NOI18N
        PartialReportSearchButton2.setText("   Buscar");

        javax.swing.GroupLayout CustomReportPanelLayout = new javax.swing.GroupLayout(CustomReportPanel);
        CustomReportPanel.setLayout(CustomReportPanelLayout);
        CustomReportPanelLayout.setHorizontalGroup(
            CustomReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomReportPanelLayout.createSequentialGroup()
                .addGroup(CustomReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustomReportPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CustomReportFromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomReportToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PartialReportSearchButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustomReportPanelLayout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CustomReportTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(347, 347, 347))
            .addGroup(CustomReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(CustomReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomReportPanelLayout.createSequentialGroup()
                        .addComponent(CustomReportPrintButton, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addGap(74, 74, 74))
                    .addGroup(CustomReportPanelLayout.createSequentialGroup()
                        .addComponent(CustomReportGenerateButton)
                        .addContainerGap())))
            .addGroup(CustomReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CustomReportPanelLayout.createSequentialGroup()
                    .addGap(363, 363, 363)
                    .addComponent(PartialReportSearchButton1)
                    .addContainerGap(363, Short.MAX_VALUE)))
        );
        CustomReportPanelLayout.setVerticalGroup(
            CustomReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PartialReportSearchButton2)
                    .addComponent(CustomReportFromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(CustomReportToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(CustomReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(CustomReportPanelLayout.createSequentialGroup()
                        .addComponent(CustomReportGenerateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CustomReportPrintButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomReportTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(CustomReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CustomReportPanelLayout.createSequentialGroup()
                    .addGap(140, 140, 140)
                    .addComponent(PartialReportSearchButton1)
                    .addContainerGap(140, Short.MAX_VALUE)))
        );

        ReportsTabbedPanel.addTab("Reporte Personalizado", CustomReportPanel);

        javax.swing.GroupLayout ReportAdminPanelLayout = new javax.swing.GroupLayout(ReportAdminPanel);
        ReportAdminPanel.setLayout(ReportAdminPanelLayout);
        ReportAdminPanelLayout.setHorizontalGroup(
            ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReportsTabbedPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
        );
        ReportAdminPanelLayout.setVerticalGroup(
            ReportAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReportsTabbedPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        AdminTabbedPanel.addTab("Reportes", ReportAdminPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminTabbedPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(AdminTabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        formWindowClosed(null);
        MainController.setVisibleAdminView(false);
    }//GEN-LAST:event_ExitButtonActionPerformed

private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
    EmployeeList.removeAll();
    String searchText = ConsultEmployeeTextField.getText();
    if (searchText.isEmpty()) {
        EmployeeList.setModel(AdministrateEmployeeController.TotalSearchOfEmployees());
    } else {
        try{
            int searchInt = Integer.parseInt(searchText);
            EmployeeList.setModel(AdministrateEmployeeController.SearchOfEmployees(searchInt));
        }catch(Exception e){
            showMessage("Advertencia","La busqueda debe hacerse por ID", JOptionPane.WARNING_MESSAGE);
        };
    }
    ConsultEmployeeTextField.setText(null);
}//GEN-LAST:event_SearchButtonActionPerformed

    public void showMessage(String title, String message, int messageType) {
        JOptionPane.showMessageDialog(rootPane, message, title, messageType);
        PlateExampleTextField.setText("");
        IdentifierPlateTextField.setText("");
        IdentifierPlateTextField.requestFocus();
    }

    public int showOptionMessage(String message) {
        int option = JOptionPane.showConfirmDialog(rootPane, message);
        return option;
    }

private void EmployeeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_EmployeeListValueChanged
    int emp = Integer.parseInt(EmployeeList.getSelectedValue().toString().substring(0, EmployeeList.getSelectedValue().toString().indexOf(" "))) - 1;
    if (emp >= 0) {
        Employee e = AdministrateEmployeeController.getEmployeeListSearch().get(emp);
        AdministrateEmployeeController.setTempEmployee(e);
        IdEmployeeTextField.setText(String.valueOf(e.getId()));
        NameEmployeeTextField.setText(e.getName());
        LastNameEmployeeTextField.setText(e.getLastName());
        DocumentEmployeeTextField.setText(e.getDocument());
        isAdminEmployeeCheckBox.setSelected(e.isAdministrator());
        isActiveEmployeeCheckBox.setSelected(e.isIsActive());
        UserTextField.setText(e.getUser());
    }
}//GEN-LAST:event_EmployeeListValueChanged

    public void setPlatesTableModel(TableModel dataModel) {
        PlatesTable.setModel(dataModel);
    }

    public void updatePlatesTable() {
        PlatesTable.updateUI();
    }

    public void setVehicleTypeComboBoxModel(ComboBoxModel aModel) {
        VehicleTypeComboBox.setModel(aModel);
    }

    public void updateVehicleTypeComboBox() {
        VehicleTypeComboBox.updateUI();
    }
    
    private void AdminTabbedPanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AdminTabbedPanelFocusGained
        VehicleTypeComboBox.setModel(AdministrateBandRates.AllVehicleTypes());
        VehicleTypeComboBox.updateUI();
        PlatesTable.setModel(AdministrateVehicleTypeController.TotalSearchOfVehicles());
        PlatesTable.updateUI();
        EmployeeList.setModel(AdministrateEmployeeController.TotalSearchOfEmployees());
        EmployeeList.updateUI();
        String id = (String) VehicleTypeComboBox.getSelectedItem();
        RatesTable.setModel(AdministrateBandRates.getModelTable(AdministrateBandRates.getVehicleTypeSelected(id)));
        RatesTable.updateUI();
    }//GEN-LAST:event_AdminTabbedPanelFocusGained

    private void CreateEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateEmployeeButtonActionPerformed
        if (flag) {
            this.setNullEmp();
            CreateEmployeeButton.setText("Guardar Empleado");
            IdEmployeeTextField.setText(String.valueOf(EmployeeManagementController.getNextID())); 
            this.setEnabledEmp(flag);
            UpdateEmployeeButton.setEnabled(false);
            flag = false;
        } else {
            int option = this.askToAdmin(create);
            if (option == JOptionPane.OK_OPTION) {
                EmployeeManagementController.saveNewEmployee(getUserID(), getLastNameEmpTF(), getNameEmpTF(), getDocumentEmpTF(), getUserTF(), getUserPass(), getConfirmUserPass(), isActiveEmployeeCheckBox.isSelected(), isAdminEmployeeCheckBox.isSelected());
                SearchButtonActionPerformed(null);
            }else if(option == JOptionPane.CANCEL_OPTION || option == 
                    JOptionPane.CLOSED_OPTION){
                        return;
            }
            CreateEmployeeButton.setText("Crear Empleado");
            this.setEnabledEmp(flag);
            UpdateEmployeeButton.setEnabled(true);
            this.setNullEmp();
            flag = true;
        }
    }//GEN-LAST:event_CreateEmployeeButtonActionPerformed

private void UpdateEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmployeeButtonActionPerformed
    if(IdEmployeeTextField.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Consulte el empleado a modificar", "Error", JOptionPane.WARNING_MESSAGE, null);
    }else{
        if (flag2) {
            UpdateEmployeeButton.setText("Guardar Cambios");
            this.setEnabledEmp(flag2);
            CreateEmployeeButton.setEnabled(false);
            flag2 = false;
        } else {
            int option = this.askToAdmin(update);
            if (option == JOptionPane.OK_OPTION) {
                EmployeeManagementController.updateOldEmployee(getUserID(), getLastNameEmpTF(), getNameEmpTF(), getDocumentEmpTF(), getUserTF(), getUserPass(), getConfirmUserPass(), isActiveEmployeeCheckBox.isSelected(), isAdminEmployeeCheckBox.isSelected());
                SearchButtonActionPerformed(null);
            }else if(option == JOptionPane.CANCEL_OPTION || option == 
                    JOptionPane.CLOSED_OPTION){
                        return;
            }
            UpdateEmployeeButton.setText("Actualizar Empleado");
            this.setEnabledEmp(flag2);
            CreateEmployeeButton.setEnabled(true);
            this.setNullEmp();
            flag2 = true;
        }
    }
}//GEN-LAST:event_UpdateEmployeeButtonActionPerformed

private void SaveParkwayChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveParkwayChangesButtonActionPerformed
    if(flag3){
        SaveParkwayChangesButton.setText("Guardar Cambios");
        this.setEnableParkway(flag3);
        flag3 = false;
    }else{
        int option = this.askToParkway();
        if(option == JOptionPane.OK_OPTION){
            //Crear
        }else if(option == JOptionPane.NO_OPTION){
            // Aquí algo para que vuelva a sus datos originales sin modificaciones
        }else if(option == JOptionPane.CANCEL_OPTION || option == JOptionPane.
                CLOSED_OPTION){
                    return;
        }
        SaveParkwayChangesButton.setText("Cambiar Datos");
        this.setEnableParkway(flag3);
        flag3 = true;
    }
}//GEN-LAST:event_SaveParkwayChangesButtonActionPerformed

private void SavePlateButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SavePlateButtonFocusGained
    PlateExampleTextField.requestFocus();
}//GEN-LAST:event_SavePlateButtonFocusGained

private void SavePlateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavePlateButtonActionPerformed
    MainController.saveNewVehicleType(IdentifierPlateTextField.getText(), PlateExampleTextField.getText());
}//GEN-LAST:event_SavePlateButtonActionPerformed

private void PlateExampleTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PlateExampleTextFieldKeyReleased
    PlateExampleTextField.setText(PlateExampleTextField.getText().toUpperCase());
}//GEN-LAST:event_PlateExampleTextFieldKeyReleased

private void PlateExampleTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PlateExampleTextFieldKeyPressed
    PlateExampleTextField.setText(PlateExampleTextField.getText().toUpperCase());
}//GEN-LAST:event_PlateExampleTextFieldKeyPressed

private void SaveRateChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveRateChangesButtonActionPerformed
    if (RatesTable.isEditing()) {
        RatesTable.getCellEditor().stopCellEditing();
    }
    String id = (String) VehicleTypeComboBox.getSelectedItem();
    for (int i=0;i<RatesTable.getRowCount();i++){
        AdministrateBandRates.rowIsEdited(i,
                String.valueOf(RatesTable.getValueAt(i, 0)),
                String.valueOf(RatesTable.getValueAt(i, 1)),
                String.valueOf(RatesTable.getValueAt(i, 2)),
                String.valueOf(RatesTable.getValueAt(i, 3)),
                String.valueOf(RatesTable.getValueAt(i, 4)),
                AdministrateBandRates.getVehicleTypeSelected(id));
    }
    
    RatesTable.setModel(AdministrateBandRates.getModelTable(AdministrateBandRates.getVehicleTypeSelected(id)));
    RatesTable.updateUI();
    
}//GEN-LAST:event_SaveRateChangesButtonActionPerformed

private void VehicleTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_VehicleTypeComboBoxItemStateChanged
    String id = (String) VehicleTypeComboBox.getSelectedItem();
    RatesTable.setModel(AdministrateBandRates.getModelTable(AdministrateBandRates.getVehicleTypeSelected(id)));
    RatesTable.updateUI();
}//GEN-LAST:event_VehicleTypeComboBoxItemStateChanged

private void EmployeeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeListMouseClicked
    EmployeeListValueChanged(null);
}//GEN-LAST:event_EmployeeListMouseClicked

private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    // "Reinicia" la clase
    flag = flag2 = flag3 = true;
    this.setNullEmp();
    this.setEnabledEmp(false);
    this.setEnableParkway(false);
    UpdateEmployeeButton.setEnabled(true);
    CreateEmployeeButton.setEnabled(true);
}//GEN-LAST:event_formWindowClosed

    private void PartialReportGenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartialReportGenerateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PartialReportGenerateButtonActionPerformed

    private void CustomReportGenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomReportGenerateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomReportGenerateButtonActionPerformed

private void DeleteLastRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteLastRateActionPerformed
    AdministrateBandRates.deleteRateFromVehicleType(VehicleTypeComboBox.getSelectedItem().toString());
}//GEN-LAST:event_DeleteLastRateActionPerformed

    private long getUserID(){
        return Long.parseLong(IdEmployeeTextField.getText());
    }

    private String getUserPass(){
        return String.valueOf(PasswordField.getPassword());
    }
    
    private String getConfirmUserPass(){
        return String.valueOf(ConfirmPasswordField.getPassword());
    }

    private String getDocumentEmpTF() {
        return DocumentEmployeeTextField.getText();
    }

    private String getLastNameEmpTF() {
        return LastNameEmployeeTextField.getText();
    }

    private String getNameEmpTF() {
        return NameEmployeeTextField.getText();
    }

    private String getUserTF() {
        return UserTextField.getText().toLowerCase();
    }
    
    private void setEnableParkway(boolean bool){
        NameParkwayTextField.setEditable(bool);
        AddressTextField.setEditable(bool);
        NITParkwayTextField.setEditable(bool);
        TelephoneTextField.setEditable(bool);
        MaxCapacityTextField.setEditable(bool);
    }
    
    private void setEnabledEmp(boolean bool) {
        NameEmployeeTextField.setEnabled(bool);
        LastNameEmployeeTextField.setEnabled(bool);
        DocumentEmployeeTextField.setEnabled(bool);
        UserTextField.setEnabled(bool);
        PasswordField.setEnabled(bool);
        ConfirmPasswordField.setEnabled(bool);
        isAdminEmployeeCheckBox.setEnabled(bool);
        isActiveEmployeeCheckBox.setEnabled(bool);
    }

    private void setNullEmp() {
        IdEmployeeTextField.setText(null);
        NameEmployeeTextField.setText(null);
        LastNameEmployeeTextField.setText(null);
        DocumentEmployeeTextField.setText(null);
        UserTextField.setText(null);
        PasswordField.setText(null);
        ConfirmPasswordField.setText(null);
        isActiveEmployeeCheckBox.setSelected(false);
        isAdminEmployeeCheckBox.setSelected(false);
    }
    
    private int askToAdmin(String message){
        return JOptionPane.showConfirmDialog(null,(message + NameEmployeeTextField.getText() + "?"));
    }
    
    private int askToParkway(){
        return JOptionPane.showConfirmDialog(null,"¿Está seguro de modificar la "
                + "información de " + NameParkwayTextField.getText() + "?");
    }
    
    public void confirmationMessages(String message,String type){
        JOptionPane.showMessageDialog(null, message,type,JOptionPane.WARNING_MESSAGE);
    }
    
    private boolean flag = true;
    private boolean flag2 = true;
    private boolean flag3 = true;
    private final String create = "¿Está seguro de crear al empleado ";
    private final String update = "¿Está seguro de modificar al empleado ";
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressParkwayLabel;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JTabbedPane AdminTabbedPanel;
    private javax.swing.JPanel AdministrateVehicles;
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JTextField ConsultEmployeeTextField;
    private javax.swing.JButton CreateEmployeeButton;
    private javax.swing.JTextField CustomReportFromTextField;
    private javax.swing.JButton CustomReportGenerateButton;
    private javax.swing.JPanel CustomReportPanel;
    private javax.swing.JButton CustomReportPrintButton;
    private javax.swing.JTable CustomReportTable;
    private javax.swing.JTextField CustomReportToTextField;
    private javax.swing.JTextField CustomReportTotalTextField;
    private javax.swing.JButton DeleteLastRate;
    private javax.swing.JLabel DocumentEmployeeLabel;
    private javax.swing.JTextField DocumentEmployeeTextField;
    private javax.swing.JPanel EmployeeAdminPanel;
    private javax.swing.JList EmployeeList;
    private javax.swing.JLabel EmployeeListLabel;
    private javax.swing.JScrollPane EmployeeListScroll;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel IdEmployeeLabel;
    private javax.swing.JTextField IdEmployeeTextField;
    private javax.swing.JTextField IdentifierPlateTextField;
    private javax.swing.JLabel LastNameEmployeeLabel;
    private javax.swing.JTextField LastNameEmployeeTextField;
    private javax.swing.JLabel MaxCapacityLabel;
    private javax.swing.JTextField MaxCapacityTextField;
    private javax.swing.JLabel NITParkwayLabel;
    private javax.swing.JTextField NITParkwayTextField;
    private javax.swing.JLabel NameEmployeeLabel;
    private javax.swing.JTextField NameEmployeeTextField;
    private javax.swing.JLabel NameParkwayLabel;
    private javax.swing.JTextField NameParkwayTextField;
    private javax.swing.JPanel ParkwayAdminPanel;
    private javax.swing.JTextField PartialReportDateTextField;
    private javax.swing.JButton PartialReportGenerateButton;
    private javax.swing.JPanel PartialReportPanel;
    private javax.swing.JButton PartialReportPrintButton;
    private javax.swing.JButton PartialReportSearchButton;
    private javax.swing.JButton PartialReportSearchButton1;
    private javax.swing.JButton PartialReportSearchButton2;
    private javax.swing.JTable PartialReportTable;
    private javax.swing.JTextField PartialReportTotalTextField;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPanel PlateAdmin;
    private javax.swing.JTextField PlateExampleTextField;
    private javax.swing.JLabel PlateSampleLabel;
    private javax.swing.JTable PlatesTable;
    private javax.swing.JPanel RateAdminPanel;
    private javax.swing.JScrollPane RatesScroll;
    private javax.swing.JTable RatesTable;
    private javax.swing.JPanel ReportAdminPanel;
    private javax.swing.JTabbedPane ReportsTabbedPanel;
    private javax.swing.JButton SaveParkwayChangesButton;
    private javax.swing.JButton SavePlateButton;
    private javax.swing.JButton SaveRateChangesButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel SearchEmployeeLabel;
    private javax.swing.JTabbedPane SubPanel;
    private javax.swing.JLabel TelephoneParkwayLabel;
    private javax.swing.JTextField TelephoneTextField;
    private javax.swing.JButton UpdateEmployeeButton;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField UserTextField;
    private javax.swing.JComboBox VehicleTypeComboBox;
    private javax.swing.JLabel VehicleTypeLabel;
    private javax.swing.JLabel VehicleTypeNameLabel;
    private javax.swing.JScrollPane VehicleTypeScroll;
    private javax.swing.JCheckBox isActiveEmployeeCheckBox;
    private javax.swing.JCheckBox isAdminEmployeeCheckBox;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
