/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CodeBarPanel.java
 *
 * Created on 19-oct-2011, 18:23:55
 */
package view;

/**
 *
 * @author miguel
 */
public class CodeBarPanel extends javax.swing.JPanel {

    /** Creates new form CodeBarPanel */
    public CodeBarPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barcode.jpg"))); // NOI18N
        add(Label, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    String path="";
    
    
}//GEN-LAST:event_formComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label;
    // End of variables declaration//GEN-END:variables
}
