package view;

import controller.ExitController;
import controller.LogoutController;
import controller.MainController;
import controller.ParkingController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author r4wd3r
 */
public class MainView extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    
    public MainView() {
        initComponents();
        PlateTextField.requestFocus();
        Clock clock = new Clock(true);
        clock.setBounds(ClockPanel.getBounds());
        clock.setVisible(true);        
        ClockPanel.add(clock);
        ClockPanel.repaint();
        ClockPanel.setVisible(false);
        ClockPanel.setVisible(true);         
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        DataEntryPanel = new javax.swing.JPanel();
        PlateTextField = new javax.swing.JTextField();
        PlateLabel = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        OptionsPanel = new javax.swing.JPanel();
        ExitButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        ParkingPanel = new javax.swing.JPanel();
        CloseBoxButton = new javax.swing.JButton();
        AdminButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        MainTablePanel = new javax.swing.JPanel();
        MainTableToolbar = new javax.swing.JToolBar();
        EntriesTableButton = new javax.swing.JButton();
        ExitsTableButton = new javax.swing.JButton();
        BillsTableButton = new javax.swing.JButton();
        BillsTurnTableButton = new javax.swing.JButton();
        TypeVehicleTableButton = new javax.swing.JButton();
        AoQPanel = new javax.swing.JPanel();
        ClockPanel = new javax.swing.JPanel();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        EditMenu = new javax.swing.JMenu();
        ViewMenu = new javax.swing.JMenu();
        HelpMenu = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChiquiParking");

        DataEntryPanel.setBackground(new java.awt.Color(255, 255, 255));

        PlateTextField.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        PlateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlateTextFieldActionPerformed(evt);
            }
        });

        PlateLabel.setFont(new java.awt.Font("Tahoma", 0, 20));
        PlateLabel.setText("Placa:");

        SearchButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.png"))); // NOI18N
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DataEntryPanelLayout = new javax.swing.GroupLayout(DataEntryPanel);
        DataEntryPanel.setLayout(DataEntryPanelLayout);
        DataEntryPanelLayout.setHorizontalGroup(
            DataEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataEntryPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(PlateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PlateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SearchButton)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        DataEntryPanelLayout.setVerticalGroup(
            DataEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataEntryPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(PlateLabel)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataEntryPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(PlateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(DataEntryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OptionsPanel.setBackground(new java.awt.Color(255, 255, 255));

        ExitButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        ExitButton.setText("  Salir");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Stop.png"))); // NOI18N
        LogoutButton.setText("Cerrar Sesión");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OptionsPanelLayout = new javax.swing.GroupLayout(OptionsPanel);
        OptionsPanel.setLayout(OptionsPanelLayout);
        OptionsPanelLayout.setHorizontalGroup(
            OptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionsPanelLayout.createSequentialGroup()
                .addContainerGap(681, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        OptionsPanelLayout.setVerticalGroup(
            OptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(OptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutButton))
                .addContainerGap())
        );

        CloseBoxButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        CloseBoxButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Box.png"))); // NOI18N
        CloseBoxButton.setText("Cerrar Turno");

        AdminButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        AdminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tools.png"))); // NOI18N
        AdminButton.setText("Administración");
        AdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48));
        jLabel6.setForeground(new java.awt.Color(51, 102, 0));
        jLabel6.setText("e-Parking");

        javax.swing.GroupLayout ParkingPanelLayout = new javax.swing.GroupLayout(ParkingPanel);
        ParkingPanel.setLayout(ParkingPanelLayout);
        ParkingPanelLayout.setHorizontalGroup(
            ParkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParkingPanelLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(AdminButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CloseBoxButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ParkingPanelLayout.setVerticalGroup(
            ParkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParkingPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ParkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CloseBoxButton)
                    .addComponent(AdminButton)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        MainTablePanel.setBackground(new java.awt.Color(153, 153, 255));

        MainTableToolbar.setRollover(true);

        EntriesTableButton.setText("Entradas");
        EntriesTableButton.setFocusable(false);
        EntriesTableButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EntriesTableButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MainTableToolbar.add(EntriesTableButton);

        ExitsTableButton.setText("Salidas");
        ExitsTableButton.setFocusable(false);
        ExitsTableButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ExitsTableButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MainTableToolbar.add(ExitsTableButton);

        BillsTableButton.setText("Facturas");
        BillsTableButton.setFocusable(false);
        BillsTableButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BillsTableButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MainTableToolbar.add(BillsTableButton);

        BillsTurnTableButton.setText("Facturas Turno");
        BillsTurnTableButton.setFocusable(false);
        BillsTurnTableButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BillsTurnTableButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MainTableToolbar.add(BillsTurnTableButton);

        TypeVehicleTableButton.setText("Tipo de Vehículos");
        TypeVehicleTableButton.setFocusable(false);
        TypeVehicleTableButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TypeVehicleTableButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MainTableToolbar.add(TypeVehicleTableButton);

        javax.swing.GroupLayout MainTablePanelLayout = new javax.swing.GroupLayout(MainTablePanel);
        MainTablePanel.setLayout(MainTablePanelLayout);
        MainTablePanelLayout.setHorizontalGroup(
            MainTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainTablePanelLayout.createSequentialGroup()
                .addComponent(MainTableToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        MainTablePanelLayout.setVerticalGroup(
            MainTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainTablePanelLayout.createSequentialGroup()
                .addComponent(MainTableToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        AoQPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout AoQPanelLayout = new javax.swing.GroupLayout(AoQPanel);
        AoQPanel.setLayout(AoQPanelLayout);
        AoQPanelLayout.setHorizontalGroup(
            AoQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        AoQPanelLayout.setVerticalGroup(
            AoQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ClockPanelLayout = new javax.swing.GroupLayout(ClockPanel);
        ClockPanel.setLayout(ClockPanelLayout);
        ClockPanelLayout.setHorizontalGroup(
            ClockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );
        ClockPanelLayout.setVerticalGroup(
            ClockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        FileMenu.setText("Archivo");
        MenuBar.add(FileMenu);

        EditMenu.setText("Editar");
        MenuBar.add(EditMenu);

        ViewMenu.setText("Ver");
        MenuBar.add(ViewMenu);

        HelpMenu.setText("Ayuda");
        MenuBar.add(HelpMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParkingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(OptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(MainTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ClockPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DataEntryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AoQPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ParkingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DataEntryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AoQPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(OptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlateTextFieldActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        LogoutController.logout(JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea cerrar sesión?" , "Cerrar Sesión" , JOptionPane.YES_NO_OPTION));
    }//GEN-LAST:event_LogoutButtonActionPerformed

private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
    ExitController.exit(JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea salir?" , "Cerrar Programa" , JOptionPane.YES_NO_OPTION));
}//GEN-LAST:event_ExitButtonActionPerformed

    private void AdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonActionPerformed
        MainController.setVisibleAdminAccessView(true);
    }//GEN-LAST:event_AdminButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminButton;
    private javax.swing.JPanel AoQPanel;
    private javax.swing.JButton BillsTableButton;
    private javax.swing.JButton BillsTurnTableButton;
    private javax.swing.JPanel ClockPanel;
    private javax.swing.JButton CloseBoxButton;
    private javax.swing.JPanel DataEntryPanel;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JButton EntriesTableButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton ExitsTableButton;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JPanel MainTablePanel;
    private javax.swing.JToolBar MainTableToolbar;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JPanel OptionsPanel;
    private javax.swing.JPanel ParkingPanel;
    private javax.swing.JLabel PlateLabel;
    private javax.swing.JTextField PlateTextField;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton TypeVehicleTableButton;
    private javax.swing.JMenu ViewMenu;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
