/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PreviewEntryTicket.java
 *
 * Created on 4/01/2012, 06:33:56 PM
 */
package view;

/**
 *
 * @author Martin Kanayet
 */
public class PreviewEntryTicket extends javax.swing.JPanel {

    /** Creates new form PreviewEntryTicket */
    public PreviewEntryTicket() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TicketNumberLabel = new javax.swing.JLabel();
        TicketNumber = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        PlateLabel = new javax.swing.JLabel();
        Plate = new javax.swing.JLabel();
        VehicleType = new javax.swing.JLabel();
        Tittle = new javax.swing.JLabel();
        ParkingName = new javax.swing.JLabel();
        ParkingAddress = new javax.swing.JLabel();
        ParkingNIT = new javax.swing.JLabel();
        AttendedByLabel = new javax.swing.JLabel();
        Employee = new javax.swing.JLabel();
        BarCodePanel = new javax.swing.JPanel();
        FootPage = new javax.swing.JLabel();

        TicketNumberLabel.setText("Tiquete número:");

        TicketNumber.setText("#####");

        DateLabel.setText("Fecha y hora:");

        Date.setText("#####");

        PlateLabel.setText("Placa:");

        Plate.setText("aaa111");

        VehicleType.setText("Tipo de vehiculo");

        Tittle.setText("Aquí va tu lindo titulo");

        ParkingName.setText("Nombre del parqueadero");

        ParkingAddress.setText("Dirección del parqueadero");

        ParkingNIT.setText("NIT del parqueadero");

        AttendedByLabel.setText("Atendido por:");

        Employee.setText("Aquí va tu lindo nombre");

        javax.swing.GroupLayout BarCodePanelLayout = new javax.swing.GroupLayout(BarCodePanel);
        BarCodePanel.setLayout(BarCodePanelLayout);
        BarCodePanelLayout.setHorizontalGroup(
            BarCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );
        BarCodePanelLayout.setVerticalGroup(
            BarCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        FootPage.setText("Aquí va tu lindo pie de página");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BarCodePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TicketNumberLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TicketNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(PlateLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Plate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(ParkingName))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ParkingAddress)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(VehicleType, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ParkingNIT))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AttendedByLabel)
                        .addGap(64, 64, 64)
                        .addComponent(Employee, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FootPage, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tittle)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TicketNumberLabel)
                    .addComponent(Date)
                    .addComponent(TicketNumber)
                    .addComponent(DateLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlateLabel)
                    .addComponent(Plate)
                    .addComponent(VehicleType))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ParkingName)
                    .addComponent(ParkingAddress))
                .addGap(18, 18, 18)
                .addComponent(ParkingNIT)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AttendedByLabel)
                    .addComponent(Employee))
                .addGap(18, 18, 18)
                .addComponent(BarCodePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(FootPage))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AttendedByLabel;
    private javax.swing.JPanel BarCodePanel;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel Employee;
    private javax.swing.JLabel FootPage;
    private javax.swing.JLabel ParkingAddress;
    private javax.swing.JLabel ParkingNIT;
    private javax.swing.JLabel ParkingName;
    private javax.swing.JLabel Plate;
    private javax.swing.JLabel PlateLabel;
    private javax.swing.JLabel TicketNumber;
    private javax.swing.JLabel TicketNumberLabel;
    private javax.swing.JLabel Tittle;
    private javax.swing.JLabel VehicleType;
    // End of variables declaration//GEN-END:variables
}
